//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH.Engine.Adapters.Karamba3D {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BH.Engine.Adapters.Karamba3D.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be converted to {1} due to Karamba&apos;s {2} property..
        /// </summary>
        internal static string ErrorBarPointLoadOrientation {
            get {
                return ResourceManager.GetString("ErrorBarPointLoadOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a convert method for {0}..
        /// </summary>
        internal static string ErrorConverterNotFound {
            get {
                return ResourceManager.GetString("ErrorConverterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cross section map path {0} was not found..
        /// </summary>
        internal static string ErrorCrossSectionMapNotFound {
            get {
                return ResourceManager.GetString("ErrorCrossSectionMapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a valid cross section profile from {1}..
        /// </summary>
        internal static string ErrorCrossSectionProfileConversion {
            get {
                return ResourceManager.GetString("ErrorCrossSectionProfileConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box cross section with different flange widths are not supported yet..
        /// </summary>
        internal static string ErrorDifferentFlangeNotSupported {
            get {
                return ResourceManager.GetString("ErrorDifferentFlangeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} array should contain 3 elements. Instead it contains {1} elements..
        /// </summary>
        internal static string ErrorInvalidVectorArray {
            get {
                return ResourceManager.GetString("ErrorInvalidVectorArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature load is not supported yet for 2d elements..
        /// </summary>
        internal static string ErrorTemperatureLoadOnSurfaces {
            get {
                return ResourceManager.GetString("ErrorTemperatureLoadOnSurfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been converted to BhOM&apos;s {1} and {2}..
        /// </summary>
        internal static string NoteStrainLoadConversion {
            get {
                return ResourceManager.GetString("NoteStrainLoadConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cross section fillet values are not supported when when the box cross section has different thicknesses or flange widths. The fillet values have not been exported..
        /// </summary>
        internal static string WarningBoxCrossSectionNotSupportedFillet {
            get {
                return ResourceManager.GetString("WarningBoxCrossSectionNotSupportedFillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cross section fillet value is not compatible with not symmetrical flanges. The value has not been exported..
        /// </summary>
        internal static string WarningICrossSectionNotSupportedFillet {
            get {
                return ResourceManager.GetString("WarningICrossSectionNotSupportedFillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported yet..
        /// </summary>
        internal static string WarningNotSupportedType {
            get {
                return ResourceManager.GetString("WarningNotSupportedType", resourceCulture);
            }
        }
    }
}
