/*
 * This file is part of the Buildings and Habitats object Model (BHoM)
 * Copyright (c) 2015 - 2024, the respective contributors. All rights reserved.
 *
 * Each contributor holds copyright over their respective contributions.
 * The project versioning (Git) records all such contribution source information.
 *                                           
 *                                                                              
 * The BHoM is free software: you can redistribute it and/or modify         
 * it under the terms of the GNU Lesser General Public License as published by  
 * the Free Software Foundation, either version 3.0 of the License, or          
 * (at your option) any later version.                                          
 *                                                                              
 * The BHoM is distributed in the hope that it will be useful,              
 * but WITHOUT ANY WARRANTY; without even the implied warranty of               
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                 
 * GNU Lesser General Public License for more details.                          
 *                                                                            
 * You should have received a copy of the GNU Lesser General Public License     
 * along with this code. If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.      
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karamba3D_Engine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karamba3D_Engine.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize the data set &quot;{0}&quot;. \nCheck that the data set file has not been altered (for example by opening it in a code editor and formatted): try building the visual studio solution `BHoM_Dataset` or re-installing BHoM.\nOtherwise, check that you are not using BHoM Nuget packages and mixing references from disk and Nuget..
        /// </summary>
        public static string DeserializationOfDataSetError {
            get {
                return ResourceManager.GetString("DeserializationOfDataSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be converted to {1} due to Karamba&apos;s {2} property..
        /// </summary>
        public static string ErrorBarPointLoadOrientation {
            get {
                return ResourceManager.GetString("ErrorBarPointLoadOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a convert method for &quot;{0}&quot;..
        /// </summary>
        public static string ErrorConversionNotFound {
            get {
                return ResourceManager.GetString("ErrorConversionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a convert method for {0}..
        /// </summary>
        public static string ErrorConverterNotFound {
            get {
                return ResourceManager.GetString("ErrorConverterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cross section map path {0} was not found..
        /// </summary>
        public static string ErrorCrossSectionMapNotFound {
            get {
                return ResourceManager.GetString("ErrorCrossSectionMapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a valid cross section profile from {1}..
        /// </summary>
        public static string ErrorCrossSectionProfileConversion {
            get {
                return ResourceManager.GetString("ErrorCrossSectionProfileConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box cross section with different flange widths are not supported yet..
        /// </summary>
        public static string ErrorDifferentFlangeNotSupported {
            get {
                return ResourceManager.GetString("ErrorDifferentFlangeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} array should contain 3 elements. Instead it contains {1} elements..
        /// </summary>
        public static string ErrorInvalidVectorArray {
            get {
                return ResourceManager.GetString("ErrorInvalidVectorArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature load is not supported yet for 2d elements..
        /// </summary>
        public static string ErrorTemperatureLoadOnSurfaces {
            get {
                return ResourceManager.GetString("ErrorTemperatureLoadOnSurfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one matching data set found for &quot;{0}&quot;. Please specify full path, OR set &quot;{1}&quot; to true. Data sets found:\n\t{2}.
        /// </summary>
        public static string MultipleCrossSectionDataSetError {
            get {
                return ResourceManager.GetString("MultipleCrossSectionDataSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data set matching &quot;{0}&quot; was found..
        /// </summary>
        public static string NoCrossSectionDataSetError {
            get {
                return ResourceManager.GetString("NoCrossSectionDataSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been converted to BhOM&apos;s {1} and {2}..
        /// </summary>
        public static string NoteStrainLoadConversion {
            get {
                return ResourceManager.GetString("NoteStrainLoadConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cross section fillet values are not supported when when the box cross section has different thicknesses or flange widths. The fillet values have not been exported..
        /// </summary>
        public static string WarningBoxCrossSectionNotSupportedFillet {
            get {
                return ResourceManager.GetString("WarningBoxCrossSectionNotSupportedFillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not currently explicitly supported. A generic section has been created. If was not possible to set a property the value has been set to NaN..
        /// </summary>
        public static string WarningCrossSectionExplicityConversionNotSupported {
            get {
                return ResourceManager.GetString("WarningCrossSectionExplicityConversionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cross section fillet value is not compatible with not symmetrical flanges. The value has not been exported..
        /// </summary>
        public static string WarningICrossSectionNotSupportedFillet {
            get {
                return ResourceManager.GetString("WarningICrossSectionNotSupportedFillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear temperature changes are not supported yet..
        /// </summary>
        public static string WarningLinearTemperatureChangesNotSupported {
            get {
                return ResourceManager.GetString("WarningLinearTemperatureChangesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not supported yet..
        /// </summary>
        public static string WarningNotYetSupportedType {
            get {
                return ResourceManager.GetString("WarningNotYetSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rotation for the local point load with the attached node is not supported yet..
        /// </summary>
        public static string WarningPointLoadLocalLoadNotSupported {
            get {
                return ResourceManager.GetString("WarningPointLoadLocalLoadNotSupported", resourceCulture);
            }
        }
    }
}
