//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karamba3D_Engine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karamba3D_Engine.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be converted to {1} due to Karamba&apos;s {2} property..
        /// </summary>
        public static string ErrorBarPointLoadOrientation {
            get {
                return ResourceManager.GetString("ErrorBarPointLoadOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a convert method for &quot;{0}&quot;..
        /// </summary>
        public static string ErrorConversionNotFound {
            get {
                return ResourceManager.GetString("ErrorConversionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a convert method for {0}..
        /// </summary>
        public static string ErrorConverterNotFound {
            get {
                return ResourceManager.GetString("ErrorConverterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cross section map path {0} was not found..
        /// </summary>
        public static string ErrorCrossSectionMapNotFound {
            get {
                return ResourceManager.GetString("ErrorCrossSectionMapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a valid cross section profile from {1}..
        /// </summary>
        public static string ErrorCrossSectionProfileConversion {
            get {
                return ResourceManager.GetString("ErrorCrossSectionProfileConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box cross section with different flange widths are not supported yet..
        /// </summary>
        public static string ErrorDifferentFlangeNotSupported {
            get {
                return ResourceManager.GetString("ErrorDifferentFlangeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} array should contain 3 elements. Instead it contains {1} elements..
        /// </summary>
        public static string ErrorInvalidVectorArray {
            get {
                return ResourceManager.GetString("ErrorInvalidVectorArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature load is not supported yet for 2d elements..
        /// </summary>
        public static string ErrorTemperatureLoadOnSurfaces {
            get {
                return ResourceManager.GetString("ErrorTemperatureLoadOnSurfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been converted to BhOM&apos;s {1} and {2}..
        /// </summary>
        public static string NoteStrainLoadConversion {
            get {
                return ResourceManager.GetString("NoteStrainLoadConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cross section fillet values are not supported when when the box cross section has different thicknesses or flange widths. The fillet values have not been exported..
        /// </summary>
        public static string WarningBoxCrossSectionNotSupportedFillet {
            get {
                return ResourceManager.GetString("WarningBoxCrossSectionNotSupportedFillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not currently explicitly supported. A generic section has been created. If was not possible to set a property the value has been set to NaN..
        /// </summary>
        public static string WarningCrossSectionExplicityConversionNotSupported {
            get {
                return ResourceManager.GetString("WarningCrossSectionExplicityConversionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cross section fillet value is not compatible with not symmetrical flanges. The value has not been exported..
        /// </summary>
        public static string WarningICrossSectionNotSupportedFillet {
            get {
                return ResourceManager.GetString("WarningICrossSectionNotSupportedFillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear temperature changes are not supported yet..
        /// </summary>
        public static string WarningLinearTemperatureChangesNotSupported {
            get {
                return ResourceManager.GetString("WarningLinearTemperatureChangesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not supported yet..
        /// </summary>
        public static string WarningNotYetSupportedType {
            get {
                return ResourceManager.GetString("WarningNotYetSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rotation for the local point load with the attached node is not supported yet..
        /// </summary>
        public static string WarningPointLoadLocalLoadNotSupported {
            get {
                return ResourceManager.GetString("WarningPointLoadLocalLoadNotSupported", resourceCulture);
            }
        }
    }
}
